#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 41-freescout-scheduler
SERVICE_NAME="freescout-scheduler"
check_container_initialized
check_service_initialized init 40-freescout
liftoff

_ts() { TZ="${TIMEZONE}" date +'%Y-%m-%d.%H:%M:%S'; }

_sleep_until_next_minute() {
    local _secs=$(( 10#$(date +%S) ))
    sleep $(( 60 - _secs ))
}

case "${SCHEDULER_LOG_TYPE,,}" in
    file )
        exec >> "${SCHEDULER_LOG_PATH%/}/${SCHEDULER_LOG_FILE}" 2>&1
    ;;
    none )
        exec > /dev/null 2>&1
    ;;
    console | *)
        exec > /proc/1/fd/1 2>&1
    ;;
esac

print_debug "FreeScout scheduler online - dispatching schedule:run at top of each minute"
_sleep_until_next_minute

while true; do
    echo "$(_ts) Scheduling Starting"
    sudo -u "${NGINX_USER}" TZ="${TIMEZONE}" php "${NGINX_WEBROOT%/}"/artisan schedule:run | \
        TZ="${TIMEZONE}" awk '{ print strftime("%Y-%m-%d.%H:%M:%S"), $0; fflush() }'
    echo "$(_ts) Scheduling Finished"
    _sleep_until_next_minute
done
