#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 40-freescout-worker
SERVICE_NAME="freescout-worker"
check_container_initialized
check_service_initialized init 40-freescout
liftoff

exec s6-setuidgid "${NGINX_USER}" /command/with-contenv bash << ENDSCRIPT
case "${WORKER_LOG_TYPE:-${SCHEDULER_LOG_TYPE}}" in
    file )
        exec >> "${WORKER_LOG_PATH%/}/${WORKER_LOG_FILE}" 2>&1
    ;;
    none )
        exec > /dev/null 2>&1
    ;;
    console | *)
        exec > /proc/1/fd/1 2>&1
    ;;
esac
exec env TZ="${TIMEZONE}" php "${NGINX_WEBROOT%/}/artisan" queue:work --queue='emails,default' --sleep=5 --tries=1 --timeout=1800
ENDSCRIPT
